apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: healthcare
data:
  APP_ENV: "development"
  PORT: "8006"
  RABBITMQ_URL: "amqp://admin:password123@rabbitmq:5672/"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "465"
  SMTP_SECURE: "true"
  SMTP_SKIP_VERIFY: "true"
  SMTP_USER: "medipulsesrilanka@gmail.com"
  EMAIL_FROM: "Healthcare Platform Notifications <medipulsesrilanka@gmail.com>"
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  namespace: healthcare
type: Opaque
data:
  # Base64 encoded: cbbg sljt pfha xlfa
  SMTP_PASS: Y2JiZyBzbGp0IHBmaGEgeGxmYQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: healthyacr2026.azurecr.io/notification-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8006
        envFrom:
        - configMapRef:
            name: notification-service-config
        - secretRef:
            name: notification-service-secret
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: healthcare
spec:
  selector:
    app: notification-service
  ports:
  - port: 8006
    targetPort: 8006
