apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-symptom-service-config
  namespace: healthcare
data:
  APP_ENV: "production"
  PORT: "8008"
  AUTH_SERVICE_URL: "http://auth-service:8001"
  DATABASE_URL: "postgres://postgres:password123@ai-symptom-db:5432/symptom_db?sslmode=disable"
  AI_PROVIDER: "gemini"
  GEMINI_MODEL: "gemini-2.5-flash"

