apiVersion: v1
kind: ConfigMap
metadata:
  name: support-service-config
  namespace: healthcare
data:
  APP_ENV: "development"
  PORT: "8011"
  DATABASE_URL: "postgres://postgres:password123@support-db:5432/support_db?sslmode=disable"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-service
  namespace: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-service
  template:
    metadata:
      labels:
        app: support-service
    spec:
      containers:
      - name: support-service
        image: healthyacr2026.azurecr.io/support-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8011
        envFrom:
        - configMapRef:
            name: support-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: support-service
  namespace: healthcare
spec:
  selector:
    app: support-service
  ports:
  - port: 8011
    targetPort: 8011
