apiVersion: v1
kind: Secret
metadata:
  name: appointment-service-secret
  namespace: healthcare
type: Opaque

stringData:
  JWT_SECRET: Z2VuZXJhdGUtYS1yZWFsLTMyLWNoYXItc2VjcmV0LWhlcmU=
  INTERNAL_API_KEY: "change-me-shared-with-patient-service"
