apiVersion: v1
kind: ConfigMap
metadata:
  name: telemedicine-service-config
  namespace: healthcare
data:
  APP_ENV: "production"
  PORT: "8009"
  APPOINTMENT_SERVICE_URL: "http://appointment-service.healthcare.svc.cluster.local:8004"
  JITSI_BASE_URL: "https://meet.jit.si"

