apiVersion: v1
kind: Service
metadata:
  name: telemedicine-db
  namespace: healthcare
  labels:
    app: telemedicine-db
spec:
  selector:
    app: telemedicine-db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

