apiVersion: v1
kind: Secret
metadata:
  name: telemedicine-service-secret
  namespace: healthcare
type: Opaque
stringData:
  JWT_SECRET: "generate-a-real-32-char-secret-here"
  DATABASE_URL: "postgres://postgres:password123@telemedicine-db.healthcare.svc.cluster.local:5432/telemedicine_db?sslmode=disable"

