apiVersion: v1
kind: Secret
metadata:
  name: file-storage-service-secret
  namespace: healthcare
type: Opaque
data:
  JWT_SECRET: Z2VuZXJhdGUtYS1yZWFsLTMyLWNoYXItc2VjcmV0LWhlcmU=
  JWT_REFRESH_SECRET: Z2VuZXJhdGUtYS1yZWFsLXJlZnJlc2gtc2VjcmV0LWhlcmU=
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=
  RABBITMQ_PASSWORD: cGFzc3dvcmQxMjM=
  CLOUDINARY_CLOUD_NAME: eW91ci1jbG91ZC1uYW1l
  CLOUDINARY_API_KEY: eW91ci1hcGkta2V5
  CLOUDINARY_API_SECRET: eW91ci1hcGktc2VjcmV0
  R2_ACCESS_KEY_ID: eW91ci1yMi1hY2Nlc3Mta2V5LWlk
  R2_SECRET_ACCESS_KEY: eW91ci1yMi1zZWNyZXQta2V5
