apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: healthcare
data:
  APP_ENV: "production"
  PORT: "8005"
  DATABASE_URL: "postgres://postgres:$(POSTGRES_PASSWORD)@postgres-service.healthcare.svc.cluster.local:5432/payment_db?sslmode=disable"
  RABBITMQ_URL: "amqp://admin:$(RABBITMQ_PASSWORD)@rabbitmq-service.healthcare.svc.cluster.local:5672/"

