apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
  namespace: healthcare
type: Opaque
# Values must be base64 encoded.
# Command to encode: echo -n "your-value" | base64
# Command to decode: echo "encoded-value" | base64 -d
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=
  RABBITMQ_PASSWORD: cGFzc3dvcmQxMjM=

